### ISSUE TITLE
ImageFromTweet Runnable Error

### ISSUE THREAD

**Issue by Yicong-Huang** [ISG-ICS/Wildfires#9]
**Describe the bug**
When launching `ImageFromTweet` Runnable, it gives the following error:

```
SQL: select id, text from records r WHERE NOT EXISTS (select distinct id from images i where i.id = r.id) limit 100
[DATABASE] HOST = cloudberry05.ics.uci.edu, CONNECTION COUNT = 13, MAXIMUM = 100
extracting [], results = []
error: Traceback (most recent call last):
  File "/extra/yicongh10/wildfires/backend/task/image_from_tweet.py", line 25, in run
    f"select id, text from records r WHERE NOT EXISTS (select distinct id from images i where i.id = r.id) limit {batch_num}")})
  File "/extra/yicongh10/wildfires/backend/task/image_from_tweet.py", line 23, in <dictcomp>
    self.dumper.insert({id: self.extractor.extract(text) for id, text in
  File "/extra/yicongh10/wildfires/backend/data_preparation/extractor/tweet_media_extractor.py", line 28, in extract
    link_type: MediaURL = URLClassifier.classify(short_url)
  File "/extra/yicongh10/wildfires/venv/lib/python3.7/site-packages/timeout_decorator/timeout_decorator.py", line 91, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "/extra/yicongh10/wildfires/venv/lib/python3.7/site-packages/timeout_decorator/timeout_decorator.py", line 150, in __call__
    return self.value
  File "/extra/yicongh10/wildfires/venv/lib/python3.7/site-packages/timeout_decorator/timeout_decorator.py", line 173, in value
    raise load
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /how-to-make-a-hydrogen-conversion-kit-at-home/ (Caused by None)```


**To Reproduce**
1. start `TaskManager`
2. start a thread for `ImageFromTweet`
3. set loop time 600, other parameter are default

**Expected behavior**
Should work without error and extract image links from tweets.

**Desktop (please complete the following information):**
 - OS: CentOS 7

**Comment by JHaoX** [comment]
The "requests" raises exceptions when the URL is invalid.
After fixing the invalid URL problem, there are more errors:
These ones came together and showed the problem with a deprecated library: PhantomJS. I have downloaded the PhantomJS, but I am not sure where to put it.
![image](https://user-images.githubusercontent.com/16579642/68075639-adbfd580-fd67-11e9-8181-ab4de2343a87.png)
![image](https://user-images.githubusercontent.com/16579642/68075685-4fdfbd80-fd68-11e9-8f5c-5a4786a0234b.png)

**Comment by Yicong-Huang** [comment]
It is fine to use phantom js, even though it is deprecated.

It is for dynamically render the html so that we can parse the content.

**Comment by JHaoX** [comment]
I found that I didn't have PhantomJS in my local bin. Mentioning it in the setup instruction could be helpful.
